[package]
name = "tui"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
vga = { path = "../vga" }
log = { path = "../log" }
keyboard = { path = "../keyboard" }
collections = { path = "../collections" }
