[package]
name = "kfs"
version = "0.1.0"
edition = "2021"
authors = [
  "Clément Saad <clement.sqf@gmail.com>",
  "Dorian Burgun <dorian@burgun.dev>",
]

[profile.dev]
panic = "abort"
strip = true

[profile.release]
panic = "abort"
