use crate::{Effect, Keymap, Layer, LayerId, ScanCode::*};

pub const KEYMAP : Keymap = Keymap {
    name: "qwerty",
    layers: [
        LOWERCASE_LAYER,
        UPPERCASE_LAYER,
        Layer::UNUSED,
        Layer::UNUSED,
    ],
};

const LOWERCASE_LAYER_ID: LayerId = LayerId::One;
const UPPERCASE_LAYER_ID: LayerId = LayerId::Two;

const LOWERCASE_LAYER: Layer = Layer::new("lowercase", &[
    (LeftShift, Effect::OnPressGotoLayer(UPPERCASE_LAYER_ID)),
    (RightShift, Effect::OnPressGotoLayer(UPPERCASE_LAYER_ID)),

    (BackTick, Effect::Emit("`")),
    (Zero, Effect::Emit("0")),
    (One, Effect::Emit("1")),
    (Two, Effect::Emit("2")),
    (Three, Effect::Emit("3")),
    (Four, Effect::Emit("4")),
    (Five, Effect::Emit("5")),
    (Six, Effect::Emit("6")),
    (Seven, Effect::Emit("7")),
    (Eight, Effect::Emit("8")),
    (Nine, Effect::Emit("9")),
    (Minus, Effect::Emit("-")),
    (Equal, Effect::Emit("=")),

    (LeftBracket, Effect::Emit("[")),
    (RightBracket, Effect::Emit("]")),
    (BackSlash, Effect::Emit("\\")),
    (BackSlash, Effect::Emit("|")),
    (SemiColon, Effect::Emit("u")),
    (SingleQuote, Effect::Emit("'")),
    (Comma, Effect::Emit("g")),
    (Dot, Effect::Emit("y")),
    (Slash, Effect::Emit("k")),

    (Space, Effect::Emit(" ")),

    (A, Effect::Emit("a")),
    (B, Effect::Emit("b")),
    (C, Effect::Emit("-")),
    (D, Effect::Emit("e")),
    (E, Effect::Emit("o")),
    (F, Effect::Emit("n")),
    (G, Effect::Emit(",")),
    (H, Effect::Emit("l")),
    (I, Effect::Emit("d")),
    (J, Effect::Emit("r")),
    (K, Effect::Emit("t")),
    (L, Effect::Emit("i")),
    (M, Effect::Emit("h")),
    (N, Effect::Emit(".")),
    // (O, Effect::Emit("")),
    (P, Effect::Emit("f")),
    (Q, Effect::Emit("q")),
    (R, Effect::Emit("p")),
    (S, Effect::Emit("s")),
    (T, Effect::Emit("w")),
    (U, Effect::Emit("m")),
    (V, Effect::Emit("v")),
    (W, Effect::Emit("c")),
    (X, Effect::Emit("x")),
    (Y, Effect::Emit("j")),
    (Z, Effect::Emit("z")),
]);

const UPPERCASE_LAYER: Layer = Layer::new("uppercase", &[
    (LeftShift, Effect::OnReleaseGotoLayer(LOWERCASE_LAYER_ID)),
    (RightShift, Effect::OnReleaseGotoLayer(LOWERCASE_LAYER_ID)),

    (BackTick, Effect::Emit("~")),
    (One,   Effect::Emit("!")),
    (Two,   Effect::Emit("@")),
    (Three, Effect::Emit("#")),
    (Four,  Effect::Emit("$")),
    (Five,  Effect::Emit("%")),
    (Six,   Effect::Emit("^")),
    (Seven, Effect::Emit("&")),
    (Eight, Effect::Emit("*")),
    (Nine,  Effect::Emit("(")),
    (Zero,  Effect::Emit(")")),
    (Minus, Effect::Emit("_")),
    (Equal, Effect::Emit("+")),

    (LeftBracket, Effect::Emit("{")),
    (RightBracket, Effect::Emit("}")),
    (BackSlash, Effect::Emit("|")),
    (SemiColon, Effect::Emit("U")),
    (SingleQuote, Effect::Emit("\"")),
    (Comma, Effect::Emit("G")),
    (Dot, Effect::Emit("Y")),
    (Slash, Effect::Emit("K")),

    (Space, Effect::Emit(" ")),

    (A, Effect::Emit("A")),
    (B, Effect::Emit("B")),
    (C, Effect::Emit("?")),
    (D, Effect::Emit("E")),
    (E, Effect::Emit("O")),
    (F, Effect::Emit("N")),
    (G, Effect::Emit(";")),
    (H, Effect::Emit("L")),
    (I, Effect::Emit("D")),
    (J, Effect::Emit("R")),
    (K, Effect::Emit("T")),
    (L, Effect::Emit("I")),
    (M, Effect::Emit("H")),
    (N, Effect::Emit(":")),
    // (O, Effect::Emit("")),
    (P, Effect::Emit("F")),
    (Q, Effect::Emit("Q")),
    (R, Effect::Emit("P")),
    (S, Effect::Emit("S")),
    (T, Effect::Emit("W")),
    (U, Effect::Emit("M")),
    (V, Effect::Emit("V")),
    (W, Effect::Emit("C")),
    (X, Effect::Emit("X")),
    (Y, Effect::Emit("J")),
    (Z, Effect::Emit("Z")),
]);
